ZZYS.Client/Controllers/SysController.cs
using Common.Configure.Basics;
using Common.Configure.Configs;
using Common.Frame;
using Common.Frame.Basic;
using Common.Frame.Cacher;
using Common.Frame.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static Common.Configure.Supports.ConfigEnums;

namespace ZZYS.Client.Controllers
{
    public class SysController : BaseController
    {
        #region 管理员登录
        [HttpGet]
        public ActionResult SysLogin()
        {
            return View();
        }
        [HttpPost]
        public JsonResult SysLogin(string phone, string pwd, string code)
        {
            if (string.IsNullOrWhiteSpace(phone)) { return Json(new { Error = true, Msg = "缺少必要参数,管理员登录账号." }); }
            if (string.IsNullOrWhiteSpace(pwd)) { return Json(new { Error = true, Msg = "缺少必要参数,管理员登录密码." }); }
            if (string.IsNullOrWhiteSpace(code)) { return Json(new { Error = true, Msg = "缺少必要参数,验证码." }); }
            var sessionCode = Session[GlobalStatic.MANAGER_LOGIN_CODE_KEY] as string;
            if (string.IsNullOrWhiteSpace(sessionCode)) { return Json(new { Error = true, Msg = "未获取到服务器验证码，请刷新页面后重试." }); }
            if (!string.Equals(sessionCode, code, StringComparison.CurrentCultureIgnoreCase)) { return Json(new { Error = true, Msg = "验证码不正确." }); }
            Session.Remove(GlobalStatic.MANAGER_LOGIN_CODE_KEY);
            var adminsConfig = GlobalStatic._AdminConfig;
            if (adminsConfig?.Administrators == null || !adminsConfig.Administrators.Any())
            {
                return Json(new { Error = true, Msg = "未获取到管理员数据,请联系技术人员." });
            }
            var adm = adminsConfig.Administrators.FirstOrDefault(e => e.Phone == phone);
            if (adm == null)
            {
                return Json(new { Error = true, Msg = "管理员账号不正确." });
            }
            if (adm.State != AnyStatus.Valid)
            {
                return Json(new { Error = true, Msg = "该账户暂无法登录." });
            }
            var isValid = Password.IsManagerPassword(adm.Password, pwd, adm.SysCode);
            if (isValid)
            {
                try
                {
                    adm.LoginIP = ClientIP;
                    adm.LastLoginTime = DateTime.Now;
                    adminsConfig.SaveConfig();
                    Session[GlobalStatic.MANAGER_KEY] = adm;
                    return Json(new { Error = false });
                }
                catch (Exception)
                {
                    //Log:
                    return Json(new { Error = true, Msg = "登录异常,请联系管理员查看服务器日志." });
                }
            }
            else
            {
                return Json(new { Error = true, Msg = "密码校验不正确." });
            }
        }
        #endregion

        #region 权限管理
        #region 管理员信息管理
        #region 管理员列表
        [HttpGet]
        public ActionResult Admins()
        {
            return View();
        }
        #endregion
        #region 修改管理员信息
        [HttpGet]
        public ActionResult ModifyAdmin(Guid id)
        {
            return View();
        }
        [HttpPost]
        public JsonResult ModifyAdmin(SysManager admin)
        {
            return Json(new { Error = false });
        }
        #endregion
        #region 修改管理员状态
        [HttpPost]
        public JsonResult SetAdminState(Guid id, AnyStatus state)
        {
            return Json(new { Error = false });
        }
        #endregion
        #region 修改管理员密码
        [HttpGet]
        public ActionResult ModifyPassword()
        {
            return View();
        }
        [HttpPost]
        public JsonResult ModifyPassword(string oldPwd, string newPwd, string smsCode)
        {
            return Json(new { Error = false });
        }
        #endregion
        #region 删除管理员
        [HttpPost]
        public JsonResult RemoveAdmin(Guid id)
        {
            return Json(new { Error = false });
        }
        #endregion
        #region 添加管理员
        [HttpGet]
        public ActionResult NewAdmin()
        {
            return View();
        }
        [HttpPost]
        public JsonResult NewAdmin(SysManager admin)
        {
            return Json(new { Error = false });
        }
        #endregion
        #endregion
        #region 角色管理
        #region 角色列表
        [HttpGet]
        public ActionResult Roles()
        {
            return View();
        }
        #endregion
        #region 添加角色
        [HttpGet]
        public ActionResult NewRole()
        {
            return View();
        }
        [HttpPost]
        public JsonResult NewRole(SysRole role)
        {
            return Json(new { Error = false });
        }
        #endregion
        #region 删除角色
        [HttpPost]
        public JsonResult RemoveRole(Guid id)
        {
            return Json(new { Error = false });
        }
        #endregion
        #region 修改角色状态
        [HttpPost]
        public JsonResult SetRoleState(Guid id, AnyStatus state)
        {
            return Json(new { Error = false });
        }
        #endregion
        #region 编辑角色权限
        [HttpGet]
        public ActionResult ModifyRole(Guid id)
        {
            return View();
        }
        [HttpPost]
        public JsonResult ModifyRole(Guid id, List<Guid> menus)
        {
            return Json(new { Error = false });
        }
        #endregion
        #endregion
        #region 权限菜单管理
        #region 菜单列表
        [HttpGet]
        public ActionResult Menus()
        {
            return View();
        }

        /// <summary>
        /// ajax加载菜单列表
        /// </summary>
        /// <param name="p">父节点编号</param>
        /// <param name="n">节点名称</param>
        /// <param name="isPager">是否分页</param>
        /// <param name="idx">页码</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult LoadMenus(Guid? p, string n, bool isPager = true, int idx = 1)
        {
            try
            {
                var allMenus = SysCacher.SystemMenuListCache.AsQueryable();

                if (p.HasValue && p.Value != Guid.Empty)
                {
                    allMenus = allMenus.Where(e => e.ParentId == p.Value);
                }
                if (!string.IsNullOrWhiteSpace(n))
                {
                    allMenus = allMenus.Where(e => e.DisplayName.Contains(n));
                }
                var clone = allMenus.Select(e => new {
                    e.DisplayName,
                    e.Href,
                    e.IsDisplay,
                    e.ICON,
                    e.TabIndex,
                    e.ParentName,
                    e.Id,
                    e.Sort
                });
                if (!isPager) return Json(new { Error = false, Data = clone });


                var tempQuery = allMenus.Select(e => new {
                    e.DisplayName,
                    e.Href,
                    e.IsDisplay,
                    e.ICON,
                    e.TabIndex,
                    e.ParentName,
                    e.Id,
                    e.Sort
                }).OrderBy(e => e.Sort);
                var result = new PagerView<dynamic>(idx);
                result.Pager(tempQuery);
                return Json(new { Error = false, Data = result });

            }
            catch (Exception)
            {
                return Json(new { Error = true, Msg = "抱歉服务器异常。LoadMenus Error" });
            }
        }
        #endregion
        #region 添加菜单
        [HttpGet]
        public ActionResult NewMenu()
        {
            return View();
        }
        [HttpPost]
        public JsonResult NewMenu(SysMenu menu)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(menu.Href))
                {
                    return Json(new { Error = true, Msg = "菜单链接地址必须填写。" });
                }
                if (string.IsNullOrWhiteSpace(menu.DisplayName))
                {
                    return Json(new { Error = true, Msg = "菜单名称必须填写。" });
                }
                var isExis = SysCacher.SystemMenuListCache.Any(e => e.DisplayName.Equals(menu.DisplayName, StringComparison.CurrentCultureIgnoreCase));
                if (isExis)
                {
                    return Json(new { Error = true, Msg = "菜单名称已存在，不能重复添加。" });
                }
                if (menu.MenuLevel == MenuLevel.None)
                {
                    return Json(new { Error = true, Msg = "必须选择菜单所属级别。" });
                }

                menu.Id = Guid.NewGuid();
                menu.State = AnyStatus.Valid;
                menu.TabIndex = $"{GIdentity.NewId}";
                //计算顶级菜单的 Sort
                var topMenuCount = SysCacher.SystemMenuListCache.Count(e => e.ParentId == GlobalStatic.DefaultParentId);
                menu.Sort = topMenuCount + 1;

                //菜单级别,如果是 顶级菜单
                if (menu.MenuLevel == MenuLevel.Top)
                {
                    if (string.IsNullOrWhiteSpace(menu.ICON))
                    {
                        menu.ICON = "el-icon-menu";
                    }
                    menu.ParentId = GlobalStatic.DefaultParentId;
                }
                else
                {
                    #region 如果不是顶级菜单,则判断所属的父节点编号是否有效
                    if (menu.ParentId == Guid.Empty || menu.ParentId == GlobalStatic.DefaultParentId)
                    {
                        return Json(new { Error = true, Msg = "非顶级菜单，必须选择所属上级菜单。" });
                    }

                    var pMenu = SysCacher.SystemMenuListCache.FirstOrDefault(e => e.Id == menu.ParentId);
                    if (pMenu == null)
                    {
                        return Json(new { Error = true, Msg = "未查询到所选的上级菜单，请刷新页面重新尝试。" });
                    }
                    #endregion

                }
                var newMenu = new SysMenu()
                {
                    Id = menu.Id,//

ZZYS.Client/Views/Sys/Menus.cshtml
@using Common.Frame;
@{
    ViewBag.Title = "权限菜单";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";

}
@section js{

    <script type="text/javascript">
        var app = new Vue({
            el: "#app",
            data: {
                SearchName: "",
                Menus: {},
                ParentMenus: [],
                SelectMenuId: ''
            },
            created: function () {
                var that = this;
                api.Ajax({
                    url: "/Sys/LoadMenus",
                    data: {
                        p: "@GlobalStatic.DefaultParentId",
                        n: that.SearchName,
                        isPager: false
                    },
                    success: function (result) {
                        console.log("result1:", result);
                        if (result.Error) {

                        } else {
                            that.ParentMenus = result.Data;
                        }
                    }
                });
                this.loadMenus(1);
            },
            methods: {
                loadMenus: function (idx) {
                    var that = this;
                    api.Ajax({
                        url: "/Sys/LoadMenus",
                        data: {
                            p: that.SelectMenuId,
                            n: that.SearchName,
                            isPager: true,
                            idx: idx,
                        },
                        success: function (result) {
                            console.log("result2:", result);
                            if (result.Error) {

                            } else {
                                that.Menus = result.Data;
                                console.log("that.menus", that);
                            }
                        }
                    });
                },
                handleCurrentChange(val) {
                    this.loadMenus(val);
                },
                Cleaning: function () {
                    this.SelectMenuId = this.SearchName = "";

                    this.loadMenus(1);
                },
                Searching: function () {
                    var that = this;
                    if (that.SelectMenuId || that.SearchName) {
                        api.Ajax({
                            url: "/Sys/LoadMenus",
                            data: {
                                p: that.SelectMenuId,
                                n: that.SearchName,
                                isPager: true,
                                idx: 1,
                            },
                            success: function (result) {
                                console.log("result2:", result);
                                if (result.Error) {

                                } else {
                                    that.Menus = result.Data;
                                    
                                }
                            }
                        });
                    } else {
                        console.log("no search text.");
                    }
                },
                goNewMenu: function () {
                    window.location.href = "/Sys/NewMenu"
                }
            }
        });
    </script>
}
<el-card>
    <div slot="header" class="clearfix">
        <strong>
            @ViewBag.Title
        </strong>
        <el-button class="top-action" icon="el-icon-plus" type="text" v-on:click="goNewMenu">
            添加权限菜单
        </el-button>
    </div>
    <el-form :inline="true">
        <el-form-item label="节点名称:">
            <el-input v-model="SearchName" placeholder="请输入要搜索的节点名称..."></el-input>
        </el-form-item>
        <el-form-item label="所属根节点:">
            <el-select v-model="SelectMenuId" clearable placeholder="请选择顶级节点...">
                <el-option v-for="menu in ParentMenus"
                           :key="menu.Id"
                           :label="menu.DisplayName"
                           :value="menu.Id">
                </el-option>
            </el-select>
        </el-form-item>
        <el-form-item>
            <el-button type="primary" v-on:click="Searching">
                <i class="el-icon-search"></i>
                查询
            </el-button>
            <el-button type="info" v-on:click="Cleaning">
                <i class="el-icon-refresh"></i>
                刷新
            </el-button>
        </el-form-item>
    </el-form>

    <el-table :data="Menus.PagerData" border>
        <el-table-column fixed
                         prop="DisplayName"
                         label="菜单名称"
                         width="150">
        </el-table-column>
        <el-table-column prop="Href"
                         label="链接地址">
        </el-table-column>
        <el-table-column prop="IsDisplay"
                         label="在列表中显示">
            <template slot-scope="scope">
                <span v-text="scope.row.IsDisplay?'显示':'不显示'"></span>
            </template>
        </el-table-column>
        <el-table-column prop="ICON"
                         label="图标">
            <template slot-scope="scope">
                <i v-bind:class="scope.row.ICON"></i>
            </template>
        </el-table-column>
        <el-table-column prop="TabIndex"
                         label="菜单标识">
        </el-table-column>
        <el-table-column prop="ParentName"
                         label="上级节点">
        </el-table-column>
        <el-table-column fixed="right"
                         label="操作"
                         width="100">
            <template slot-scope="scope">
                <el-button type="text" size="small">查看</el-button>
                <el-button type="text" size="small">编辑</el-button>
            </template>
        </el-table-column>
    </el-table>


    <el-row type="flex" justify="center" v-bind:align="'middle'">
        <el-col :span="24" style="text-align:right;">
            <el-pagination layout="total,prev, pager, next"
                           v-on:current-change="handleCurrentChange"
                           :page-size="Menus.PageSize"
                           :total="Menus.DataCount">
            </el-pagination>
        </el-col>
    </el-row>
</el-card>

ZZYS.Client/Views/Sys/NewMenu.cshtml
@using Common.Frame
@using Common.Configure.Supports
@{
    ViewBag.Title = "添加权限菜单";
    ViewBag.TabIndex = "Menus";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@section js{
    <script type="text/javascript">
        var app = new Vue({
            el: "#app",
            data: {
                DefaultParentId: "@GlobalStatic.DefaultParentId",
                TotalMenus: [],
                DisplayMenus: [],
                MenuDisabed: false,
                TabIndexDisabled: true,
                MenuLevel: 0,
                Levels: [
                    { Text: "顶级菜单", Val: 0 },
                    { Text: "二级菜单", Val: 1 },
                    { Text: "功能按钮", Val: 2 }
                ],
                Menu: {
                    DisplayName: "",
                    ICON: "",
                    IsDisplay: true,
                    ParentId: '',
                    TabIndex: "",
                    Href: "javascript:;"
                },
                MenuRules: {
                    DisplayName: [
                        { required: true, message: '菜单名称必须填写.' },
                        { min: 2, max: 5, message: '长度在 2 到 5 个汉字.' },
                        { pattern: /^[\u4e00-\u9fa5]+$/, message: '菜单名称只能是中文.' }
                    ],
                    TabIndex: [
                        { required: false, message: '菜单名称必须填写.' },
                        { min: 4, max: 20, message: '长度在 4 到 20 个字符.' },
                        { pattern: /[a-zA-Z]{4,10}/, message: '长度在 4 到 10 个字母.' },
                    ],
                    Href: [
                        { required: true, message: '链接地址必须填写.' }
                    ],
                    ParentId: [
                        { required: false, message: '必须选择所属父节点.' }
                    ]
                }
            },
            created: function () {
                var that = this;
                api.Ajax({
                    url: "/Sys/LoadMenus",
                    data: {
                        isPager: false
                    },
                    success: function (result) {
                        console.log("result", result);
                        if (result.Error) {
                            this.notify("初始化错误", "获取初始化数据失败，请稍后刷新页面重试。", "error");
                        } else {
                            that.TotalMenus = result.Data;
                            that.DisplayMenus = that.TotalMenus.filter(that.filterMenus);
                            that.lvChanged(0);
                            console.log("this.displayMenus", that.DisplayMenus);
                        }
                    }
                });

            },
            methods: {
                notify: function (title, msg, type) {
                    this.$notify({
                        title: title,
                        message: msg,
                        position: 'bottom-right',
                        type: type
                    });
                },
                alert: function (title, msg, call) {
                    this.$alert(msg, title, {
                        confirmButtonText: '确定',
                        callback: call
                    });
                },
                onSubmit: function (frmName) {
                    this.$refs[frmName].validate((valid) => {
                        if (valid) {
                            this.saveMenu();
                        } else {
                            this.notify("校验失败", "填写的数据校验失败，请检查填写的内容有效性。", "warning");
                            return;
                        }
                    });
                },
                lvChanged: function (val) {
                    this.TabIndexDisabled = val === 1 ? false : true;
                    if (!this.TabIndexDisabled) {
                        this.MenuRules.TabIndex[0].required = true;
                    } else {
                        this.MenuRules.TabIndex[0].required = false;
                    }
                    if (val === 0) {
                        this.MenuDisabed = true;
                        this.DisplayMenus = [{
                            Id: this.DefaultParentId,
                            DisplayName: "顶级菜单"
                        }];
                        this.MenuRules.ParentId[0].required = false;
                    } else {
                        this.MenuRules.ParentId[0].required = true;
                        this.MenuDisabed = false;
                        this.MenuLevel = val;
                        this.DisplayMenus = this.TotalMenus.filter(this.filterMenus);
                    }
                    this.Menu.ParentId = "";
                    this.Menu.TabIndex = "";
                },
                filterMenus: function (m) {
                    if (this.MenuLevel > 0) {
                        return m.MenuLevel === this.MenuLevel - 1;
                    }
                },
                parentChanged: function (parentId) {
                    var pMenu = this.TotalMenus.find(function (m) {
                        return m.Id === parentId;
                    });
                    if (pMenu && pMenu.MenuLevel === 1) {
                        this.Menu.TabIndex = pMenu.TabIndex;
                    } else {
                        this.Menu.TabIndex = "";
                    }
                },
                saveMenu: function () {
                    var that = this;
                    api.Ajax({
                        url: "/Sys/NewMenu",
                        data: that.Menu,
                        success: function (result) {
                            if (result.Error) {
                                this.notify("添加失败", result.Msg, "error");
                            } else {
                                that.alert("保存成功",
                                    "新的菜单项已保存.(请到联系管理员编辑角色对应的权限信息)",
                                    () => {
                                        window.location.href = "@Url.Action("Menus","Sys")";
                                    });
                            }
                        }
                    });
                },
                forback: function () {
                    window.location.href = '@Url.Action("Menus","Sys")';
                }

            }
        });
    </script>
}

<el-card>
    <div slot="header" class="clearfix">
        <strong>
            @ViewBag.Title
        </strong>
    </div>

    <el-row type="flex" justify="center">
        <el-col :span="12">

            <el-form ref="frmMenu" :model="Menu" label-width="120px" size="small">
                <el-form-item label="菜单名称:" prop="DisplayName" :rules="MenuRules.DisplayName">
                    <el-input v-model="Menu.DisplayName" auto-complete="off"></el-input>
                </el-form-item>

                <el-form-item label="图标:" prop="ICon">
                    <el-input v-model="Menu.ICON" auto-complete="off"></el-input>
                </el-form-item>

                <el-form-item label="是否显示:" prop="IsDisplay">
                    <el-switch v-model="Menu.IsDisplay"></el-switch>
                </el-form-item>

                <el-form-item label="菜单级别:" prop="MenuLevel">
                    <el-radio-group v-model="MenuLevel" v-on:change="lvChanged">
                        <el-radio-button v-for="lv in Levels" :key="lv.Val" :label="lv.Val">
                            <span v-text="lv.Text"></span>
                        </el-radio-button>
                    </el-radio-group>
                </el-form-item>

                <el-form-item label="上级菜单:" prop="ParentId" :rules="MenuRules.ParentId">
                    <el-select v-model="Menu.ParentId"
                               :disabled="MenuDisabed"
                               v-on:change="parentChanged"
                               placeholder="请选择菜单的父节点...">
                        <el-option v-for="menu in DisplayMenus"
                                   :key="menu.Id"
                                   :label="menu.DisplayName"
                                   :value="menu.Id">
                            <i v-show="menu.ICON" :class="menu.ICON"></i>
                            <span v-text="menu.DisplayName"></span>
                        </el-option>
                    </el-select>
                </el-form-item>

                <el-form-item label="链接地址:" prop="Href" :rules="MenuRules.Href">
                    <el-input v-model="Menu.Href" auto-complete="off"></el-input>
                </el-form-item>

                <el-form-item label="菜单标示:" prop="TabIndex" :rules="MenuRules.TabIndex">
                    <el-input :disabled="TabIndexDisabled" v-model="Menu.TabIndex" auto-complete="off"></el-input>
                </el-form-item>

                <el-form-item>
                    <el-button type="primary" v-on:click="onSubmit('frmMenu')" icon="el-icon-plus">添加菜单</el-button>
                    <el-button v-on:click="forback">
                        返回列表
                    </el-button>
                </el-form-item>
            </el-form>

        </el-col>
    </el-row>

</el-card>

ZZYS.Client/Views/Sys/SysLogin.cshtml
@using Common.Configure.Abstracts
@using Common.Configure.Configs
@using Common.Frame
@{
    var globalConfig = GlobalStatic._GlobalConfig;
}
<!DOCTYPE html>
<html class="no-js" lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <link rel="apple-touch-icon" href="">
    <title>@globalConfig.CompanyName</title>
    <link href="~/Content/js/vendor/modernizr/normalize.min.css" rel="stylesheet" />
    <link href="~/Content/css/login.css" rel="stylesheet" />
</head>
<body>
    <section class="login">
        <div class="clearfix">
            <div class="larger-header" id="larger-header">
                <canvas id="login-canvas"></canvas>
                <div class="login-box">
                    <h3>@globalConfig.AppName</h3>
                    <p class="error"></p>
                    <form action="#" name="login" class="logon_inof" method="post">
                        <div class="input_outer">
                            <span class="u u_user"></span>
                            <input name="logname" value="13137730951" maxlength="11" tabindex="1" autofocus autocomplete="off" class="text ipt" type="text" placeholder="请输入管理员账户...">
                        </div>
                        <div class="input_outer">
                            <span class="u u_pwd"></span>
                            <input name="logpass" value="123456" maxlength="20" onfocus="this.type='password'" tabindex="2" class="text ipt" autocomplete="off" type="text" placeholder="请输入密码...">
                        </div>
                        <div class="input_outer">
                            <span class="u u_code"></span>
                            <input name="logcode" tabindex="3" maxlength="6" class="text ipt" autocomplete="off" type="text" placeholder="请输入验证码...">
                            <span class="code">
                                <img class="code-img" src="/Sys/ImageCode?codeType=sys_login_code&t=@DateTime.Now.Ticks" />
                            </span>
                        </div>
                        <div class="actions">
                            <button type="button" class="act-but submit" >
                                <i class=""></i>
                                登录
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <script src="~/Content/js/login/TweenLite.min.js"></script>
    <script src="~/Content/js/login/EasePack.min.js"></script>
    <script src="~/Content/js/plugins.js"></script>
    <script src="~/Content/js/login/login.js"></script>
</body>
</html>